Chequear que las variables no estén vacías

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,6 +6,8 @@ msg() { echo ":: $@"; }
 
 msg2() { echo "-> $@"; }
 
+error() { echo "ERROR: $@"; }
+
 if [ "${ip}" = 'cambiar' ]; then
     msg 'Tenés que configurar al menos la IP del nodo (en config)'
     exit 1
@@ -19,6 +21,18 @@ msg2 "La dirección del nodo es ${address} (siempre es mejor un dominio que una 
 msg2 "La red del nodo será ${ip}${subnet}"
 msg2 "Si no es correcto presione ^C para cancelar"
 read pause
+
+vars=""
+for var in id vpn rango_vpn node address ip subnet; do
+    if [ -z "${!var}" ]; then
+        vars="${vars}${var} "
+    fi
+done
+
+if [ ${#vars} -gt 0 ]; then
+    error "Las variables están vacías: ${vars}"
+    exit 1
+fi
 
 msg "Creando configuración"
 msg2 "Creando directorio"
@@ -62,7 +76,7 @@ fi
 
 host_files=$(shopt -s nullglob; echo ${hosts}/${node}*)
 
-tar --remove-files -czf ${vpn}.tar.gz ${vpn}/
+tar --remove-files -cvzf ${vpn}.tar.gz ${vpn}/
 
 msg2 "La configuración se encuentra en ${vpn}.tar.gz"
 msg2 "Descomprimir en /etc/tinc"
